### ISSUE TITLE
[Typo] Minor typo in 62.Matrices.annotated.pdf

### ISSUE THREAD

**Issue by Nico769** [mlvu/mlvu.github.io#3]
Hello,

There is a minor typo in the annotated version of the lecture slides `62.Matrices.annotated.pdf`. It should say "[...] the dot products of the rows of A with the **columns of B**. [...]".

![immagine](https://user-images.githubusercontent.com/12734334/77627405-2148c600-6f47-11ea-981e-ecce270df0b4.png)

Thank you for sharing your lectures!

Cheers.

**Comment by pbloem** [comment]
Thanks for the pointer. Should be fixed now.

I doubt it's the only mistake, especially in the annotations, but I'll fix them when I can.
