### ISSUE TITLE
Minor typo in 42.ProbabilisticModels2.annotated.pdf

### ISSUE THREAD

**Issue by basvandenbroek** [mlvu/mlvu.github.io#4]
I think there’s a minor typo in slide 23, I believe the derivative shouldn't have minus sign.

**Comment by pbloem** [comment]
Thanks for the pointer, that's always appreciated. However, this looks correct to me as it is. The minus comes from the second term in the first line. Maybe I'm missing something though.

**Comment by basvandenbroek** [comment]
Thank you for your reply. I thought the minus got cancelled, but I'm probably mistaken.
![derivative_of_log_likelihood](https://user-images.githubusercontent.com/10399756/99382156-62258e80-28cc-11eb-979b-a14825a98f46.jpeg)

**Comment by pbloem** [comment]
No, my bad. You're totally right! I missed the -1 you get from the second factor when you apply the chain rule inside the sum. Thanks for the correction, I'll fix this.

**Comment by pbloem** [comment]
Should be fixed now, thanks again.

523d94c9925c2a9617634c4dd1f2071de2443459
