### ISSUE TITLE
Typo in 00.Preliminaries.key-stage-0076anim3.svg

### ISSUE THREAD

**Issue by tteodorescu0** [mlvu/mlvu.github.io#6]
Location: [mlvu.github.io](https://github.com/mlvu/mlvu.github.io)/[preliminaries](https://github.com/mlvu/mlvu.github.io/tree/master/preliminaries)/00.Preliminaries.key-stage-0076anim3.svg

Issue: Typo in the derivative below. The right hand side should be $3ax^2+b$.

<img width="221" alt="Screenshot 2023-02-05 at 8 39 07 PM" src="https://user-images.githubusercontent.com/16628089/216862603-0d27ab2c-b2ca-4bc9-8ddf-b0e3df171ca5.png">

**Comment by pbloem** [comment]
Thanks for the pointer! Should be fixed soon (it'll take a while for pages to update).
