### ISSUE TITLE
Conditional independence - potential typo?

### ISSUE THREAD

**Issue by renti04** [mlvu/mlvu.github.io#7]
In Lecture 0: Preliminaries - Probability, [slide 121](https://mlvu.github.io/preliminaries#slide-121) says

p(A, B|G) = p(A|B) p(B|G)

Should this be 

p(A, B|G) = p(A|**G**) p(B|G)?

**Comment by pbloem** [comment]
Yes, thanks for the pointer. It should be fixed soon.
